server:
  port: 8086
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: game-info
  application:
    name: SI-Exam-Monitor

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defualtZone: http://localhost:8761/eureka